# Kubernetes HPA configuration v2 for visualization service
# Requires metrics-server v0.6+ installed in cluster
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: visualization-service-hpa
  namespace: matter-platform
  labels:
    app: matter-platform
    service: visualization
    tier: backend

spec:
  # Target the visualization service deployment
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: visualization-service

  # High availability with controlled scaling limits
  minReplicas: 2
  maxReplicas: 10

  # Resource utilization metrics for scaling decisions
  metrics:
    # CPU-based scaling at 70% utilization
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    
    # Memory-based scaling at 80% utilization
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

  # Fine-grained scaling behavior control
  behavior:
    # Aggressive scale up for responsiveness
    scaleUp:
      # 60s stabilization window prevents rapid fluctuations
      stabilizationWindowSeconds: 60
      policies:
        # Add up to 2 pods every 60 seconds
        - type: Pods
          value: 2
          periodSeconds: 60

    # Conservative scale down to prevent thrashing
    scaleDown:
      # 5 minute stabilization window prevents premature scale down
      stabilizationWindowSeconds: 300
      policies:
        # Remove 1 pod every 60 seconds
        - type: Pods
          value: 1
          periodSeconds: 60