apiVersion: v1  # kubernetes v1
kind: Namespace
metadata:
  name: matter-platform
  labels:
    name: matter-platform
    app: matter-satellite-platform
    environment: production
    istio-injection: enabled  # Enables Istio service mesh integration
    security-tier: restricted
    monitoring: enabled
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: environment=production  # Production node selection
    net.beta.kubernetes.io/network-policy: default-deny  # Default deny all ingress/egress
    istio.io/rev: stable  # Use stable Istio revision
    policy.matter.io/security-zone: restricted  # Custom security zone annotation
    backup.matter.io/schedule: daily  # Daily backup schedule
    monitoring.matter.io/scrape: "true"  # Enable Prometheus scraping