apiVersion: v1
kind: Secret
metadata:
  name: matter-platform-secrets
  namespace: matter-platform
  labels:
    app: matter-satellite-platform
    environment: production
    security-tier: restricted
    encryption: required
  annotations:
    last-rotated: "2024-01-16T00:00:00Z"  # Current timestamp for initial creation
    rotation-schedule: "30d"
    secret-source: aws-secrets-manager
    encryption.kubernetes.io/kms-key: "arn:aws:kms:us-west-2:123456789012:key/matter-platform-secrets-key"

type: Opaque

data:
  # Authentication secrets
  JWT_SECRET: "{{resolve:secretsmanager:matter/platform/jwt:SecretString:secret}}"
  AUTH0_CLIENT_SECRET: "{{resolve:secretsmanager:matter/platform/auth0:SecretString:client_secret}}"
  
  # External service API keys
  MAPBOX_API_KEY: "{{resolve:secretsmanager:matter/platform/mapbox:SecretString:api_key}}"
  EARTH_N_API_KEY: "{{resolve:secretsmanager:matter/platform/earth-n:SecretString:api_key}}"
  
  # Database credentials
  REDIS_PASSWORD: "{{resolve:secretsmanager:matter/platform/redis:SecretString:password}}"
  POSTGRES_PASSWORD: "{{resolve:secretsmanager:matter/platform/postgres:SecretString:password}}"
  
  # AWS credentials for service integrations
  AWS_ACCESS_KEY_ID: "{{resolve:secretsmanager:matter/platform/aws:SecretString:access_key_id}}"
  AWS_SECRET_ACCESS_KEY: "{{resolve:secretsmanager:matter/platform/aws:SecretString:secret_access_key}}"