# apiVersion: v1 - Core Kubernetes API version for ServiceAccount resource definition
apiVersion: v1
kind: ServiceAccount

metadata:
  # Service account name for Matter platform services
  name: matter-platform-sa
  # Target namespace for service account deployment
  namespace: matter-platform
  
  labels:
    app: matter-satellite-platform
    environment: production
    component: service-account
    managed-by: kubernetes
    security-tier: platform
    
  annotations:
    # AWS IAM role integration for EKS
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/matter-platform-role
    # Security controls
    kubernetes.io/enforce-mountable-secrets: "true"
    security.matter.com/secret-rotation: "enabled"
    security.matter.com/audit-logging: "enabled"
    security.matter.com/access-review: "required"

# Enable automatic token mounting for pod authentication
automountServiceAccountToken: true

# Private registry authentication
imagePullSecrets:
  - name: matter-platform-registry