apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: matter-platform
  labels:
    app: jaeger
    component: monitoring
    part-of: matter-satellite-platform
  annotations:
    security.matter.io/compliance: "enabled"
    backup.matter.io/retention: "7d"
    monitoring.matter.io/priority: "high"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: jaeger
        component: monitoring
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "16686"
        security.matter.io/scan-status: "verified"
    spec:
      serviceAccountName: matter-platform-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.35
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 16686
              name: ui
              protocol: TCP
            - containerPort: 6831
              name: jg-compact-trft
              protocol: UDP
            - containerPort: 6832
              name: jg-binary-trft
              protocol: UDP
            - containerPort: 5778
              name: config-rest
              protocol: TCP
            - containerPort: 9411
              name: zipkin
              protocol: TCP
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
            - name: MEMORY_MAX_TRACES
              value: "50000"
            - name: SAMPLING_STRATEGIES_FILE
              value: "/etc/jaeger/sampling/sampling.json"
            - name: METRICS_STORAGE_TYPE
              value: "prometheus"
            - name: LOG_LEVEL
              value: "info"
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: "/"
              port: 16686
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: "/"
              port: 16686
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jaeger-sampling-config
              mountPath: /etc/jaeger/sampling
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: jaeger-sampling-config
          configMap:
            name: jaeger-sampling
        - name: tmp
          emptyDir: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: monitoring
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: "monitoring"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"